# Generated by Django 4.1.5 on 2023-01-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('plate_id', models.TextField(db_column='plate_ID', primary_key=True, serialize=False)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('plate_type', models.TextField(blank=True, null=True)),
                ('screen_id', models.TextField(blank=True, db_column='screen_ID', null=True)),
            ],
            options={
                'db_table': 'plate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.TextField(db_column='project_ID', primary_key=True, serialize=False)),
                ('project_type', models.TextField(blank=True, null=True)),
                ('screening_start_date', models.TextField(blank=True, null=True)),
                ('sample_count', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('receptor_id', models.TextField(db_column='receptor_ID', primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('variant', models.TextField(blank=True, null=True)),
                ('ar_name', models.TextField(blank=True, db_column='AR_name', null=True)),
                ('allele_sequence', models.TextField(blank=True, null=True)),
                ('gene_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receptor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('or_field', models.TextField(blank=True, db_column='OR', null=True)),
                ('firefly', models.FloatField(blank=True, db_column='Firefly', null=True)),
                ('renilla', models.FloatField(blank=True, db_column='Renilla', null=True)),
                ('normalized', models.FloatField(blank=True, db_column='Normalized', null=True)),
                ('project', models.TextField(blank=True, db_column='Project', null=True)),
                ('plate', models.TextField(blank=True, db_column='Plate', null=True)),
                ('renilla_bgnorm', models.FloatField(blank=True, db_column='Renilla_bgnorm', null=True)),
                ('firefly_bgnorm', models.FloatField(blank=True, db_column='Firefly_bgnorm', null=True)),
                ('plate_type', models.TextField(blank=True, db_column='plate-type', null=True)),
                ('background_subtracted', models.FloatField(blank=True, db_column='Background_Subtracted', null=True)),
                ('background_divided', models.FloatField(blank=True, db_column='Background_Divided', null=True)),
                ('control_type', models.TextField(blank=True, null=True)),
                ('exp_datetime', models.TextField(blank=True, db_column='exp datetime', null=True)),
                ('prog', models.TextField(blank=True, db_column='PROG', null=True)),
                ('proj', models.TextField(blank=True, db_column='PROJ', null=True)),
                ('row', models.TextField(blank=True, db_column='Row', null=True)),
                ('column', models.FloatField(blank=True, db_column='Column', null=True)),
                ('conc', models.FloatField(blank=True, null=True)),
                ('ar', models.TextField(blank=True, db_column='AR', null=True)),
                ('well_id', models.TextField(db_column='well_ID', primary_key=True, serialize=False)),
                ('screen_type', models.TextField(blank=True, null=True)),
                ('plate_0', models.ForeignKey(blank=True, db_column='plate_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.plate')),
            ],
            options={
                'db_table': 'well',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.TextField(db_column='screen_ID', primary_key=True, serialize=False)),
                ('screen_type', models.TextField(blank=True, null=True)),
                ('control_type', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.project')),
            ],
            options={
                'db_table': 'screen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('plate', models.ForeignKey(blank=True, db_column='plate_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.plate')),
                ('well', models.ForeignKey(blank=True, db_column='well_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.well')),
            ],
            options={
                'db_table': 'sample',
                'managed': True,
            },
        ),
    ]
