# Generated by Django 4.1.5 on 2023-02-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_id', models.CharField(max_length=100)),
                ('screening_start_date', models.DateTimeField()),
                ('plate_type', models.CharField(max_length=100)),
                ('screen_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('screening_start_date', models.DateTimeField()),
                ('sample_count', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultsFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=100)),
                ('screening_start_date', models.DateTimeField()),
                ('concentration', models.FloatField()),
                ('well_id', models.CharField(max_length=100)),
                ('plate_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.CharField(max_length=100)),
                ('screen_type', models.CharField(max_length=100)),
                ('screening_start_date', models.DateTimeField()),
                ('project_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar', models.CharField(max_length=100)),
                ('concentration', models.FloatField()),
                ('firefly', models.FloatField()),
                ('renilla', models.FloatField()),
                ('normalized', models.FloatField()),
                ('screen_id', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=100)),
                ('row', models.CharField(max_length=100)),
                ('column', models.IntegerField()),
                ('receptor_name', models.CharField(max_length=100)),
                ('renilla_bgnorm', models.FloatField()),
                ('firefly_bgnorm', models.FloatField()),
                ('background_subtracted', models.FloatField()),
                ('background_divided', models.FloatField()),
                ('plate_type', models.CharField(max_length=100)),
                ('screening_start_date', models.DateTimeField()),
                ('project_type', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=100)),
                ('screen_type', models.CharField(max_length=100)),
                ('plate_id', models.CharField(max_length=100)),
                ('well_id', models.CharField(max_length=100)),
                ('sample_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectCsv',
        ),
    ]
