# Generated by Django 4.1.5 on 2023-01-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboCSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OR', models.CharField(max_length=100)),
                ('conc', models.CharField(max_length=100)),
                ('Project', models.CharField(max_length=100)),
                ('Plate', models.CharField(max_length=100)),
                ('Row', models.CharField(max_length=100)),
                ('Plate_type', models.CharField(max_length=100)),
                ('Exp_datetime', models.CharField(max_length=100)),
                ('Column', models.FloatField()),
                ('Renilla_bgnorm', models.FloatField()),
                ('Firefly_bgnorm', models.FloatField()),
                ('Background_Subtracted', models.FloatField()),
                ('Background_Divided', models.FloatField()),
                ('Firefly', models.FloatField()),
                ('Renilla', models.FloatField()),
                ('Normalized', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectCsv',
        ),
    ]
