# Generated by Django 4.1.5 on 2023-01-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboCSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OR', models.CharField(max_length=100)),
                ('conc', models.CharField(max_length=100)),
                ('Project', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectCsv',
        ),
    ]
