# Generated by Django 4.1.5 on 2023-01-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcsv',
            options={'verbose_name_plural': 'MyFiles'},
        ),
    ]
