# Generated by Django 4.1.5 on 2023-01-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0002_combocsvdata_delete_projectcsv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combocsvdata',
            old_name='OR',
            new_name='ar',
        ),
        migrations.RenameField(
            model_name='combocsvdata',
            old_name='conc',
            new_name='concentration',
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Firefly',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
