# Generated by Django 4.1.5 on 2023-01-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0002_combocsvdata_project_delete_projectcsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.TextField(db_column='screen_ID', primary_key=True, serialize=False)),
                ('screen_type', models.TextField(blank=True, null=True)),
                ('control_type', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='upload_csv.project')),
            ],
        ),
    ]
