# Generated by Django 4.1.5 on 2023-01-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0002_combocsvdata_delete_projectcsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Background_Divided',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Background_Subtracted',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Column',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Exp_datetime',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Firefly',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Firefly_bgnorm',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Normalized',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Plate',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Plate_type',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Renilla',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Renilla_bgnorm',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Row',
        ),
        migrations.RemoveField(
            model_name='combocsvdata',
            name='conc',
        ),
    ]
