# Generated by Django 4.1.5 on 2023-01-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0002_alter_projectcsv_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcsv',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='csv_files/'),
        ),
    ]
