# Generated by Django 4.1.5 on 2023-02-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0003_screen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='screen',
            old_name='control_type',
            new_name='screening_start_date',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='created_at',
        ),
    ]
