# Generated by Django 4.1.5 on 2023-01-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0003_alter_projectcsv_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcsv',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectcsv',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectcsv',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projectcsv',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='projectcsv',
            name='project_id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcsv',
            name='project_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcsv',
            name='sample_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcsv',
            name='screening_start_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
