# Generated by Django 4.1.5 on 2023-01-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0003_remove_combocsvdata_background_divided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combocsvdata',
            name='Project',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='conc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
