# Generated by Django 4.1.5 on 2023-01-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0004_alter_combocsvdata_firefly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combocsvdata',
            name='Firefly',
        ),
    ]
