# Generated by Django 4.1.5 on 2023-01-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0004_combocsvdata_project_combocsvdata_conc'),
    ]

    operations = [
        migrations.AddField(
            model_name='combocsvdata',
            name='Background_Divided',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Background_Subtracted',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Column',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Exp_datetime',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Firefly',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Firefly_bgnorm',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Normalized',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Plate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Plate_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Renilla',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Renilla_bgnorm',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combocsvdata',
            name='Row',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
