# Generated by Django 4.1.5 on 2023-02-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0006_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=100)),
                ('screening_start_date', models.CharField(max_length=100)),
                ('concentration', models.CharField(max_length=100)),
                ('well_id', models.CharField(max_length=100)),
                ('plate_id', models.CharField(max_length=100)),
            ],
        ),
    ]
